# Generated by Django 4.2 on 2023-04-07 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inbound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_amount', models.IntegerField(verbose_name='입고 수량')),
                ('inbound_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'inbound',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, verbose_name='상품 코드')),
                ('name', models.CharField(max_length=32, verbose_name='상품이름')),
                ('description', models.TextField(verbose_name='상품설명')),
                ('price', models.IntegerField(verbose_name='상품 가격')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('F', 'Free')], max_length=1)),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Outbound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_amount', models.IntegerField(verbose_name='출고 수량')),
                ('outbound_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ManyToManyField(to='erps.product')),
            ],
            options={
                'db_table': 'outbound',
            },
        ),
        migrations.CreateModel(
            name='Invetory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inbound_amount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erps.inbound')),
                ('outbound_amount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erps.outbound')),
            ],
            options={
                'db_table': 'inventory',
            },
        ),
        migrations.AddField(
            model_name='inbound',
            name='product',
            field=models.ManyToManyField(to='erps.product'),
        ),
    ]
